
name: Update Resume Gist

on: 
    push:
        paths:
        - 'resume-working-master.json'
jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 58e9ff9ad9dc8fc33a48961b4e18b4d9
        gist_file_name: resume.json
        file_path: resume-working-master.json
